# Generated by Django 4.2.4 on 2023-09-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_newuser_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='usuario',
            field=models.CharField(max_length=250),
        ),
    ]
