# Generated by Django 4.2.4 on 2023-09-11 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0013_alter_documento_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Ayudante', 'Ayudante'), ('Docente', 'Docente'), ('CoordinadorDocente', 'Coordinador Docente'), ('PuntoEstudiantil', 'Punto Estudiantil'), ('Dara', 'Dara')], max_length=30)),
                ('temp_pass', models.CharField(blank=True, max_length=30, null=True)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.sede')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.AlterField(
            model_name='ayudantesevento',
            name='ayudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.userprofile'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ayudantes',
            field=models.ManyToManyField(to='Core.userprofile'),
        ),
    ]
