# Generated by Django 4.2.4 on 2023-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_userprofile_delete_newuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='area',
            field=models.CharField(choices=[('Financiamiento', 'Financiamiento'), ('IDI', 'IDI'), ('CoordinacionDocente', 'CoordinacionDocente'), ('AsuntosEstudiantiles', 'AsuntosEstudiantiles'), ('Dara', 'Dara')], max_length=255),
        ),
    ]
