# Generated by Django 4.2.4 on 2023-09-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_alter_documento_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asistenciaevento',
            name='nombre_asistente',
        ),
        migrations.RemoveField(
            model_name='horariosala',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='horariosala',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='mimetype',
        ),
        migrations.AddField(
            model_name='documento',
            name='semestre',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='nombre',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horariosala',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='horariosala',
            name='hora_fin',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='horariosala',
            name='hora_inicio',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='horariosala',
            name='nombreDocente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horariosala',
            name='seccion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horariosala',
            name='siglaAsignatura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prestamoproducto',
            name='estado',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='nombre',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tne',
            name='estado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tne',
            name='temp_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asistenciaevento',
            name='rut_asistente',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='documento',
            name='area',
            field=models.CharField(choices=[('Financiamiento', 'Financiamiento'), ('IDI', 'IDI'), ('CoordinacionDocente', 'CoordinacionDocente'), ('AsuntosEstudiantiles', 'AsuntosEstudiantiles'), ('Dara', 'Dara')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='horariosala',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='horariosala',
            name='semana',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prestamoproducto',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tne',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tne',
            name='identificador_tarjeta',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='tne',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tne',
            name='rut',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('fecha', models.DateField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.horariosala')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.carrera'),
        ),
        migrations.AddField(
            model_name='documento',
            name='malla_curricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.mallacurricular'),
        ),
    ]
