# Generated by Django 4.2.4 on 2023-10-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_rename_cantidad_producto_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='formato_imagen',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
