# Generated by Django 4.2.4 on 2023-10-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_producto_formato_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='formato_imagen',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='noimage.jpg', upload_to='productos/'),
        ),
    ]
