# Generated by Django 4.2.4 on 2023-10-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoproducto',
            name='rut',
            field=models.CharField(db_index=True, default=1, max_length=12),
            preserve_default=False,
        ),
    ]
