# Generated by Django 4.2.4 on 2023-10-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_prestamoproducto_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamoproducto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='prestamoproducto',
            name='nombre',
            field=models.CharField(db_index=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
