# Generated by Django 4.2.4 on 2023-10-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_remove_prestamoproducto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='edificio',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='tipo',
        ),
    ]
