# Generated by Django 4.2.4 on 2023-10-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_sala_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioSalaExcepcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, db_index=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, db_index=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, db_index=True, null=True)),
                ('semana', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sigla_seccion', models.CharField(max_length=255)),
                ('docente', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_hora', models.CharField(db_index=True, max_length=8)),
                ('tipo_programacion', models.CharField(db_index=True, max_length=10)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sala')),
            ],
        ),
        migrations.RenameField(
            model_name='horariosala',
            old_name='nombreDocente',
            new_name='docente',
        ),
        migrations.RemoveField(
            model_name='horariosala',
            name='email',
        ),
        migrations.RemoveField(
            model_name='horariosala',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='horariosala',
            name='siglaAsignatura',
        ),
        migrations.AddField(
            model_name='horariosala',
            name='sigla_seccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariosala',
            name='tipo_hora',
            field=models.CharField(db_index=True, default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariosala',
            name='tipo_programacion',
            field=models.CharField(db_index=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horariosala',
            name='fecha',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariosala',
            name='semana',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
