# Generated by Django 4.2.4 on 2023-10-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0034_remove_horariosala_dias_remove_horariosala_docente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosala',
            name='semestre',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariosalaexcepcional',
            name='semestre',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
