# Generated by Django 4.2.4 on 2023-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0036_alter_horariosala_semestre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTNE',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=60, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, null=True, verbose_name='Apellido')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tne',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tne',
            name='identificador_tarjeta',
        ),
        migrations.RemoveField(
            model_name='tne',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='tne',
            name='temp_pass',
        ),
        migrations.AddField(
            model_name='tne',
            name='apellido',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='tne',
            name='codigo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tne',
            name='condicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tne',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='tne',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Llegada'),
        ),
        migrations.AlterField(
            model_name='tne',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tne',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Pendiente'),
        ),
        migrations.AlterField(
            model_name='tne',
            name='nombre',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tne',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='RUT'),
        ),
    ]
