# Generated by Django 4.2.4 on 2023-09-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_newuser_rol_alter_newuser_temp_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
