# Generated by Django 4.2.4 on 2023-09-06 22:03

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_newuser_nombre_alter_newuser_usuario'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ayudante', 'Ayudante'), ('Docente', 'Docente'), ('CoordinadorDocente', 'Coordinador Docente'), ('PuntoEstudiantil', 'Punto Estudiantil'), ('Dara', 'Dara')], max_length=30),
        ),
    ]
