# Generated by Django 4.2.4 on 2023-09-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_newuser_managers_remove_newuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
