# Generated by Django 4.2.4 on 2023-09-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_documento_documento_alter_documento_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='documento',
            new_name='archivo',
        ),
    ]
