# Generated by Django 4.2.4 on 2023-09-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_carrera_mallacurricular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='semestre',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('Teatro', 'Teatro'), ('Computación', 'Computación'), ('Normal', 'Normal')], max_length=255),
        ),
    ]
