# Generated by Django 4.2.4 on 2023-10-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0030_horariosala_dia_horariosalaexcepcional_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariosala',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horariosalaexcepcional',
            name='dia',
        ),
        migrations.AddField(
            model_name='horariosala',
            name='dias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='horariosalaexcepcional',
            name='dias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
