# Generated by Django 4.2.4 on 2023-10-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0031_remove_horariosala_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosala',
            name='dias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariosalaexcepcional',
            name='dias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
