# Generated by Django 4.2.4 on 2023-10-19 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0032_alter_horariosala_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosala',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.sala'),
        ),
        migrations.AlterField(
            model_name='horariosalaexcepcional',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.sala'),
        ),
    ]
