# Generated by Django 4.2.4 on 2023-10-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0035_horariosala_semestre_horariosalaexcepcional_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosala',
            name='semestre',
            field=models.CharField(db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='horariosalaexcepcional',
            name='semestre',
            field=models.CharField(db_index=True, max_length=1),
        ),
    ]
